ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS canvas_width INTEGER NOT NULL DEFAULT 1536,
  ADD COLUMN IF NOT EXISTS canvas_height INTEGER NOT NULL DEFAULT 1024,
  ADD COLUMN IF NOT EXISTS column_gap INTEGER NOT NULL DEFAULT 280;